### ISSUE TITLE
Maven Build Error

### ISSUE THREAD

**Issue by mzattera** [jmformenti/face-recognition-java#1]
I was always looking for a pre-trained easy to use face-recognition package for Java, this seems exactly what I needed. Unfortunately, trying to build the library I get an error and no JAR is created. Maybe you can put an already made JAR in a release?

Error log is attached.

[trace.txt](https://github.com/jmformenti/face-recognition-java/files/10095840/trace.txt)

**Comment by jmformenti** [comment]
Added the release [v0.1.0](https://github.com/jmformenti/face-recognition-java/releases/tag/v0.1.0)

**Comment by mzattera** [comment]
THANKS! a lot for the super quick reaction.

However I keep having the same error when lunching the program. It looks like a missing dependency maybe, but I am not knowledgeable in Spring enough to figure that out.

[trace.txt](https://github.com/jmformenti/face-recognition-java/files/10095930/trace.txt)

**Comment by jmformenti** [comment]
I see, It seems related to windows path (I tested in linux),  later I'll try to find a fix.

**Comment by jmformenti** [comment]
Released v0.1.1, now it should work, if not please let me know.
In addition, if you want to build from scratch you need to run `git lfs install` (I forgot to put in the README).

**Comment by mzattera** [comment]
Tests from command line works like a charm, THANKS! 🥇 
I'll look into the code to see how to incorporate this in my code.
I realised I did a very bad report, without mentioning my OS and JRE, but glad you figured that out anyway. 👍

**Comment by jmformenti** [comment]
You can use the jar as another library (I'm thinking to put it into maven central)
I recommend you to see the [test](https://github.com/jmformenti/face-recognition-java/blob/master/src/test/java/org/atypical/face/service/FaceRecognitionServiceTest.java) in order to see how create an embedding and then use it to do the prediction.

**Comment by jmformenti** [comment]
Created #2 to facilitate use the code in other projects.
